spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/product
    # driver-class-name:
    username: postgres
    password: password

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8093

entitymanager:
  packagesToScan: com.shoppingcart